# Generated by Django 3.1.6 on 2021-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210216_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
