# Generated by Django 3.1.6 on 2021-02-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('context', models.TextField()),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.ImageField(upload_to='homepage/')),
            ],
        ),
    ]
