# Generated by Django 3.1.6 on 2021-02-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210228_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='basket_items',
        ),
        migrations.AddField(
            model_name='basketitems',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basket_basket_items', related_query_name='basket_basket_items', to='order.basket'),
        ),
    ]
